# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # use bento's xenial boxen
  config.vm.box = "bento/ubuntu-16.04"

  # name it
  config.vm.hostname = 'artly-xenial'
  # artly top level folder is 3 levels up from build-support/ubuntu/xenial
  # sync it to /tmp/artly
  config.vm.synced_folder "../../..", "/tmp/artly"

  # disable audio
  config.vm.provider :virtualbox do |vb|
     vb.customize [
       "modifyvm", :id,
       "--audio", "none"
    ]
  end

  # Provision build tools with a shell script provisioner
  config.vm.provision "shell", inline: <<-SHELL
# setup apt-cacher-ng proxy
cat << EOF > /etc/apt/apt.conf.d/000-apt-cacher-ng-proxy
Acquire::http::Proxy "http://10.0.2.2:3142";
EOF

# update apt catalog
apt-get update

# misc tools: mc, tree emacs
apt-get \
  install \
    --yes \
    mc \
    tree \
    emacs-nox

# add debian build tools
apt-get \
  install \
    --yes \
    build-essential \
    devscripts \
    debhelper \
    debmake \
    automake

# pull in latest changes
# handle grub update
# https://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt
unset UCF_FORCE_CONFFOLD
export UCF_FORCE_CONFFNEW=YES
ucf --purge /boot/grub/menu.lst
export DEBIAN_FRONTEND=noninteractive
apt-get \
  -o Dpkg::Options::="--force-confnew" \
  --fix-broken \
  --show-upgraded \
  --yes \
  dist-upgrade

# autoremove all unnecessary packages
apt-get \
  --yes \
  autoremove

# reboot
reboot

  SHELL

  # check if this box has an update
  config.vm.box_check_update = true

end
