#!/usr/bin/env bash

# turn on tracing of error, this will bubble up all the error codes
# basically this allows the ERR trap is inherited by shell functions
set -o errtrace;
# turn on quiting on first error
set -o errexit;
# error out on undefined variables
set -o nounset;
# propagate pipe errors
set -o pipefail;
# debugging
#set -o xtrace;

# get script name
TMP_SCRIPT_NAME=$(basename "${0}");
# get full path of the script folder
TMP_SCRIPT_FOLDER="$(cd $(dirname $0); pwd)";
# full script path
TMP_SCRIPT_PATH="${0}";
# path to artly core folder
TMP_ARTLY_CORE_FOLDER_PATH="";

# ............................................................................ #
# print script usage
function usage {
    echo "\
Artly - automated repository tool

Usage: ${TMP_SCRIPT_NAME} [OPTIONS] <COMMAND> [COMMAND OPTIONS]

Get help for any given command using: ${TMP_SCRIPT_NAME} <COMMAND> --help

Commands:

    make-key
        Create GPG key to be used for signing of a repository.

    make-debian-repository
        Create Debian repository.

    document-debian-repository
        Generate Debian repository with READMEs containing repository setup
        instructions as well as HTML directory indexes for browsing.

    publish-github-pages
        Publish repository to GitHub Pages.

    help
        Print this usage.

Options:

    --ubuntu-packages
        Print \"apt-get install\" with all packages required by artly.

    -h, --help
        Print this usage.
";

}


# ............................................................................ #
# main entry point, checks commands and processes arguments and commands
# no traps here, since we do not need arror reporting
# :{1}: command or option to run
function begin {

    # check for commands we use and error out if they are not found
    check_commands;

    # process script arguments
    process_script_commands_and_arguments "$@";

}


# ........................................................................... #
# get script commands and argument and process them
function process_script_commands_and_arguments {

    local script_command;

    # if no arguments given print usage
    if [ $# -eq 0 ]; then
        # print usage to stderr since no valid command was provided
        usage 1>&2;
        echo "No command or arguments given">&2;
        exit 2;
    fi

    # get the script command
    script_command="${1}";
    shift;

    # run specific commands based on each command
    case "${script_command}" in

        make-key)
             ARTLY_PLUGIN="${TMP_SCRIPT_NAME} ${script_command}" \
             "${TMP_ARTLY_CORE_FOLDER_PATH}/artly-make-key.sh" "$@";
             exit;
            ;;

        make-debian-repository)
             ARTLY_PLUGIN="${TMP_SCRIPT_NAME} ${script_command}" \
             "${TMP_ARTLY_CORE_FOLDER_PATH}/artly-make-debian-repository.sh" "$@";
             exit;
            ;;

        document-debian-repository)
             ARTLY_PLUGIN="${TMP_SCRIPT_NAME} ${script_command}" \
             "${TMP_ARTLY_CORE_FOLDER_PATH}/artly-document-debian-repository.sh" "$@";
             exit;
             ;;

        publish-github-pages)
             ARTLY_PLUGIN="${TMP_SCRIPT_NAME} ${script_command}" \
             "${TMP_ARTLY_CORE_FOLDER_PATH}/artly-publish-github-pages.sh" "$@";
             exit;
             ;;

        --ubuntu-packages)
            ubuntu_packages;
            exit;
            ;;


        --help | -h | help)
            usage;
            exit 1;
            ;;

        --)
            # is the end marker from getopt
            shift;
            # there should not be any trailing params
            if [ "${#}" -gt 0 ]; then
                # print usage to stderr since no valid command was provided
                usage 1>&2;
                echo "Unknown command or arguments(s) '$@' given">&2;
                exit 2;
            else
                # if it 0 then break the loop, so the shift at the end
                # of the for loop did not cause an error
                break;
            fi
            ;;

        -*)
            # print usage to stderr since no valid command was provided
            usage 1>&2;
            echo "Unknown command or argument(s) '${1}' given.">&2;
            exit 2;
            ;;

        *)
            # print usage to stderr since no valid command was provided
            usage 1>&2;
            echo "No command or argument given">&2;
            exit 2;
            ;;
    esac;

}


# checks for all the commands required for setup and activate
# this does not include the python commands we install
function check_commands {

    # check for bash 4
    cmd_exists_bash4_or_abort;

    # check for a whole set of commands
    cmds_exists_or_abort "echo" "basename" "dirname" "readlink";

}


# ............................................................................ #
# ubuntu packages requirewd by artly
function ubuntu_packages {
    echo "apt-get install coreutils findutils sed gnupg wget aptly jq haveged \
git";
}


# ........................................................................... #
# find the core folder for artly. this is necessary because artly top level
# wrapper is symlinked in various distributions
# this will dereference artly path completely, and and look for core folder at
# the final target parent folder
# :return: echo out the full path to artly core
function _find_core_folder {

    local symlink_target;

    # detected the artly "core/"" folder containing it's scripts
    if [ -h "${TMP_SCRIPT_PATH}" ]; then
        symlink_target=$(readlink -fn "${TMP_SCRIPT_PATH}");
        echo $(dirname "${symlink_target}")/core;
    else
        echo "${TMP_SCRIPT_FOLDER}/core";
    fi
}


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ #
# TMP_ARTLY_CORE_FOLDER_PATH set BEFORE 'begin' runs by _find_core_folder
# because we need to find the core for utils.sh (and all other artly commands)
TMP_ARTLY_CORE_FOLDER_PATH="$(_find_core_folder)";

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ #
# import utils.sh
if [ -f "${TMP_ARTLY_CORE_FOLDER_PATH}/utils.sh" ]; then
    source "${TMP_ARTLY_CORE_FOLDER_PATH}/utils.sh"
else
    echo "
Could not load required '${TMP_ARTLY_CORE_FOLDER_PATH}/utils.sh' module.

" >&2;
    exit 1;
fi


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ #
begin "$@";
